outpout_dir: models/
prediction_dir: training_prediction/
input_path: /workspace/project/ssh_mapping/data_inputs_5days.nc
target_path: /workspace/project/ssh_mapping/data_target.nc
data_split: [85,15]
pretrained: True
log_dir: "log"
loss: "MSE"
gpu_device: 0
lr: 1e-4
batch_size: 32
epochs: 20
workers: 8
seed: 123
tbp: 8888
auto_eval: True