outpout_dir: models/
prediction_dir: training_inference/

# inputs_path: data/data_inputs_5days.nc
inputs_path: data/data_inputs.nc
target_path: data/data_target.nc
name_var_inputs: ssh
name_var_target: ssh

# https://github.com/ocean-data-challenges/2020a_SSH_mapping_NATL60?tab=readme-ov-file
test_start: "2012-10-22"
test_end: "2012-12-02"
data_split: [90,10]

train_start: "2013-01-02"
train_end: "2013-09-30"

model_architecture: SimpleAutoencoderCNN3D
depth: 6

log_dir: "log"
loss: "MSE"
gpu_device: 0
lr: 1e-4
batch_size: 8
epochs: 150

workers: 8
seed: 123
tbp: 8888

name_diag: Diag_OSSE
write_netcdf: True
animate: True
compute_metrics: True